version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
      - echo Installing dependencies...
      - yarn install --frozen-lockfile
  pre_build:
    commands:
      - echo Linting...
      - yarn lint
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build



