version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
      - echo Installing project dependencies...
      - yarn install
  build:
    commands:
      - echo Building project...
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: 'build/'


